# Generated by Django 4.1.7 on 2023-12-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdatamodel',
            table='api_userdatamodel',
        ),
    ]
