# Generated by Django 4.1.7 on 2023-12-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata_api', '0002_alter_userdatamodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
