# Generated by Django 4.1.7 on 2023-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdata_api', '0003_alter_userdatamodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
